Fix crash when no `-e`
`tox-envfile` has begun crashing when `tox` is run without any `-e`
argument:

```terminal
Traceback (most recent call last):
  ...
  File ".../.tox/.tox/lib/python3.8/site-packages/tox_envfile/main.py", line 13, in tox_configure
    for env in config.option.env:
TypeError: 'NoneType' object is not iterable
```

I have no idea what changed in `tox-envfile` to cause this to start
happening, but this commit attempts to fix the issue.